import productImages from "./productImages"

export const productList = [
    {id: "PRO-001", name: "Bracelet - Wikipedia", price: 64, gemstone: ["BLACK OPAL"], image: productImages.PRO_001},
    {id: "PRO-002", name: "Jewellery Store South Africa", price: 70, gemstone: ["BICOLOR SAPPHIRE", "BERYL", "SAPPHIRE"], image: productImages.PRO_002},
    {id: "PRO-003", name: "Buy BESTVECH Name Pendant Chain", price: 69, gemstone: ["BERYL"], image: productImages.PRO_003},
    {id: "PRO-004", name: "Jewellery - Wikipedia", price: 75, gemstone: ["AUSTRALIAN OPAL"], image: productImages.PRO_004},
    {id: "PRO-005", name: "Heart Pendants Set", price: 65, gemstone: ["AQUAMARINE"], image: productImages.PRO_005},
    {id: "PRO-006", name: "Koko Petite Yellow Gold Jewellery Set", price: 66, gemstone: ["AMMOLITE"], image: productImages.PRO_006},
    {id: "PRO-007", name: "Coco Avant Chanel jewellery collection", price: 77, gemstone: ["ANDALUSITE", "SUNSTONE", "BERYL"], image: productImages.PRO_007},
    {id: "PRO-008", name: "Family Jewelry, Hand Cut Coin", price: 64, gemstone: ["AMBER"], image: productImages.PRO_008},
    {id: "PRO-009", name: "China Earring Necklace Jewelry Set ", price: 81, gemstone: ["AMETHYST"], image: productImages.PRO_009},
    {id: "PRO-010", name: "Creative Jewelry Business Names", price: 79, gemstone: ["JADEITE"], image: productImages.PRO_010},
    {id: "PRO-011", name: "FUJIN Personalized Couple Jewelry Set", price: 85, gemstone: ["PREHNITE"], image: productImages.PRO_011},
    {id: "PRO-012", name: "Size Bharatnatyam Jewellery Set", price: 88, gemstone: ["SAPPHIRE", "JADEITE", "AMBER"], image: productImages.PRO_012},
    {id: "PRO-013", name: "Indian wedding jewelry sets", price: 92, gemstone: ["SODALITE"], image: productImages.PRO_013},
    {id: "PRO-014", name: "Jewels 4 Girls", price: 74, gemstone: ["STAR RUBY"], image: productImages.PRO_014},
    {id: "PRO-015", name: "Never Seen Before Jewellery Set Designs", price: 68, gemstone: ["STAR RUBY"], image: productImages.PRO_015},
    {id: "PRO-016", name: "Complete Bharatanatyam Jewellery Full", price: 75, gemstone: ["SUNSTONE"], image: productImages.PRO_016},
    {id: "PRO-017", name: "Many Names Gold Plated Christmas Gifts", price: 100, gemstone: ["BASRA PEARLS", "SAPPHIRE"], image: productImages.PRO_017},
    {id: "PRO-018", name: "18 Best Designer Jewelry Brands 2020", price: 150, gemstone: ["CARNELIAN"], image: productImages.PRO_018},
    {id: "PRO-019", name: "Christening Day Personalised Jewellery", price: 102, gemstone: ["CHRYSOBERYL"], image: productImages.PRO_019},
    {id: "PRO-020", name: "50 Unique Jewelry Store Names", price: 111, gemstone: ["FLUORITE"], image: productImages.PRO_020},
    {id: "PRO-021", name: "Bracelet - Wikipedia", price: 64, gemstone: ["BLACK OPAL"], image: productImages.PRO_021},
    {id: "PRO-022", name: "Jewellery Store South Africa", price: 70, gemstone: ["BICOLOR SAPPHIRE", "BERYL", "SAPPHIRE"], image: productImages.PRO_022},
    {id: "PRO-023", name: "Buy BESTVECH Name Pendant Chain", price: 69, gemstone: ["BERYL"], image: productImages.PRO_023},
    {id: "PRO-024", name: "Jewellery - Wikipedia", price: 75, gemstone: ["AUSTRALIAN OPAL"], image: productImages.PRO_024},
    {id: "PRO-025", name: "Heart Pendants Set", price: 65, gemstone: ["AQUAMARINE"], image: productImages.PRO_025},
    {id: "PRO-026", name: "Koko Petite Yellow Gold Jewellery Set", price: 66, gemstone: ["AMMOLITE"], image: productImages.PRO_026},
    {id: "PRO-027", name: "Coco Avant Chanel jewellery collection", price: 77, gemstone: ["ANDALUSITE", "SUNSTONE", "BERYL"], image: productImages.PRO_027},
    {id: "PRO-028", name: "Family Jewelry, Hand Cut Coin", price: 64, gemstone: ["AMBER"], image: productImages.PRO_028},
    {id: "PRO-029", name: "China Earring Necklace Jewelry Set ", price: 81, gemstone: ["AMETHYST"], image: productImages.PRO_029},
    {id: "PRO-030", name: "Creative Jewelry Business Names", price: 79, gemstone: ["JADEITE"], image: productImages.PRO_030},
    {id: "PRO-031", name: "FUJIN Personalized Couple Jewelry Set", price: 85, gemstone: ["PREHNITE"], image: productImages.PRO_031},
    {id: "PRO-032", name: "Size Bharatnatyam Jewellery Set", price: 88, gemstone: ["SAPPHIRE", "JADEITE", "AMBER"], image: productImages.PRO_032},
    {id: "PRO-033", name: "Indian wedding jewelry sets", price: 92, gemstone: ["SODALITE"], image: productImages.PRO_033},
    {id: "PRO-034", name: "Jewels 4 Girls", price: 74, gemstone: ["STAR RUBY"], image: productImages.PRO_034},
    {id: "PRO-035", name: "Never Seen Before Jewellery Set Designs", price: 68, gemstone: ["STAR RUBY"], image: productImages.PRO_035},
    {id: "PRO-036", name: "Complete Bharatanatyam Jewellery Full", price: 75, gemstone: ["SUNSTONE"], image: productImages.PRO_036},
    {id: "PRO-037", name: "Many Names Gold Plated Christmas Gifts", price: 100, gemstone: ["BASRA PEARLS", "SAPPHIRE"], image: productImages.PRO_037},
    {id: "PRO-038", name: "18 Best Designer Jewelry Brands 2020", price: 150, gemstone: ["CARNELIAN"], image: productImages.PRO_038},
    {id: "PRO-039", name: "Christening Day Personalised Jewellery", price: 102, gemstone: ["CHRYSOBERYL"], image: productImages.PRO_039},
    {id: "PRO-040", name: "50 Unique Jewelry Store Names", price: 111, gemstone: ["FLUORITE"], image: productImages.PRO_040}
]